import { MATERIAL_CATALOG, getMaterialFieldId, getMaterialOptionLabel } from "./material-catalog.js";

export const createFormulationSchema = () => ({
  fields: [
    ...MATERIAL_CATALOG.map((material) => ({
      id: getMaterialFieldId(material.id),
      kind: "number",
      label: getMaterialOptionLabel(material.id),
      description: `${material.category} from ${material.supplier}.`,
      defaultValue: 0,
      min: 0,
      max: 100,
      step: material.step ?? 1,
      unit: "% w/w",
    })),
    {
      id: "extruderbrand",
      kind: "category",
      label: "Extruder brand",
      required: true,
      defaultValue: "Process_11",
      options: [
        { label: "Process_07", value: "Process_07" },
        { label: "Process_09", value: "Process_09" },
        { label: "Process_11", value: "Process_11" },
      ],
      readOnly: true,
    },
    {
      id: "extrusionspeed",
      kind: "number",
      label: "Extrusion speed (RPM)",
      required: true,
      defaultValue: 15,
      min: 1,
      max: 60,
      step: 1,
      readOnly: true,
    },
    {
      id: "printerbrand",
      kind: "category",
      label: "Printer brand",
      required: true,
      defaultValue: "good_bot_4025-mp",
      options: [
        { label: "good_bot_2024-xp", value: "good_bot_2024-xp" },
        { label: "good_bot_2025-rx", value: "good_bot_2025-rx" },
        { label: "good_bot_4025-mp", value: "good_bot_4025-mp" },
      ],
      readOnly: true,
    },
    {
      id: "platetemperature",
      kind: "number",
      label: "Plat. temperature (°C)",
      required: true,
      defaultValue: 50,
      min: 20,
      max: 120,
      step: 1,
      readOnly: true,
    },
    {
      id: "printingspeed",
      kind: "number",
      label: "Printing speed (mm/s)",
      required: true,
      defaultValue: 30,
      min: 1,
      max: 80,
      step: 1,
      readOnly: true,
    },
    {
      id: "objecttype",
      kind: "category",
      label: "Object",
      required: true,
      defaultValue: "tablet",
      options: [
        { label: "Tablet", value: "tablet" },
        { label: "Capsule", value: "capsule" },
        { label: "Implant", value: "implant" },
      ],
      readOnly: true,
    },
    {
      id: "shape",
      kind: "category",
      label: "Shape",
      required: true,
      defaultValue: "cylinder",
      options: [
        { label: "Cylinder", value: "cylinder" },
        { label: "Capsule", value: "capsule" },
        { label: "Ring", value: "ring" },
      ],
      readOnly: true,
    },
    {
      id: "surfacearea",
      kind: "number",
      label: "Surface Area (mm²)",
      required: true,
      defaultValue: 1114.01,
      min: 0,
      max: 5000,
      step: 0.01,
      readOnly: true,
    },
    {
      id: "volume",
      kind: "number",
      label: "Volume (mm³)",
      required: true,
      defaultValue: 554.26,
      min: 0,
      max: 5000,
      step: 0.01,
      readOnly: true,
    },
    {
      id: "mediavolume",
      kind: "number",
      label: "Media volume (mm³)",
      required: true,
      defaultValue: 500,
      min: 10,
      max: 5000,
      step: 1,
      readOnly: true,
    },
    {
      id: "mediaph",
      kind: "number",
      label: "Media pH",
      required: true,
      defaultValue: 3,
      min: 1,
      max: 14,
      step: 0.1,
      readOnly: true,
    },
  ],
  reports: [
    {
      id: "prediction",
      kind: "formulation-prediction",
      label: "Prediction",
      description: "Prediction summary and dissolution profile.",
      source: "prediction",
    },
  ],
});
