import { BACKENDS, CLASSIFIER_LABELS } from "./shared/model.js";

export const FORM_SCHEMA = {
  fields: [
    {
      id: "release-name",
      kind: "text",
      label: "Release name",
      description: "Text field with the standard built-in text restrictions.",
      required: true,
      defaultValue: "Atlas rollout",
      placeholder: "Nova release",
      minLength: 4,
      maxLength: 24,
      pattern: "^[A-Za-z0-9 _\\-]+$",
    },
    {
      id: "training-epochs",
      kind: "number",
      label: "Training epochs",
      description: "Numeric field used by all backends to derive their prediction.",
      required: true,
      defaultValue: 12,
      min: 1,
      max: 120,
      step: 1,
      unit: "epochs",
    },
    {
      id: "confidence-threshold",
      kind: "number",
      label: "Confidence threshold",
      description: "Minimum confidence score to accept a recommendation. Shown as a range slider.",
      defaultValue: 0.75,
      min: 0,
      max: 1,
      step: 0.05,
      unit: "%",
    },
    {
      id: "human-approval",
      kind: "boolean",
      label: "Human approval",
      description: "Boolean field with explicit labels.",
      required: true,
      defaultValue: true,
      trueLabel: "Approved",
      falseLabel: "Blocked",
    },
    {
      id: "channel-prototype",
      kind: "number",
      label: "Prototype feature",
      hidden: true,
      inactiveFieldPolicy: "include",
    },
    {
      id: "channel-canary",
      kind: "number",
      label: "Canary feature",
      hidden: true,
      inactiveFieldPolicy: "include",
    },
    {
      id: "channel-regional",
      kind: "number",
      label: "Regional feature",
      hidden: true,
      inactiveFieldPolicy: "include",
    },
    {
      id: "channel-production",
      kind: "number",
      label: "Production feature",
      hidden: true,
      inactiveFieldPolicy: "include",
    },
    {
      id: "deployment-channel",
      kind: "mapped-category",
      label: "Deployment channel",
      description: "Mapped category field that expands a single choice into hidden one-hot features.",
      required: true,
      defaultValue: "canary",
      options: [
        {
          label: "Prototype",
          value: "prototype",
          mapping: {
            "channel-prototype": 1,
            "channel-canary": 0,
            "channel-regional": 0,
            "channel-production": 0,
          },
        },
        {
          label: "Canary",
          value: "canary",
          mapping: {
            "channel-prototype": 0,
            "channel-canary": 1,
            "channel-regional": 0,
            "channel-production": 0,
          },
        },
        {
          label: "Regional",
          value: "regional",
          mapping: {
            "channel-prototype": 0,
            "channel-canary": 0,
            "channel-regional": 1,
            "channel-production": 0,
          },
        },
        {
          label: "Production",
          value: "production",
          mapping: {
            "channel-prototype": 0,
            "channel-canary": 0,
            "channel-regional": 0,
            "channel-production": 1,
          },
        },
      ],
    },
    {
      id: "evaluation-date",
      kind: "date",
      label: "Evaluation date",
      description: "Date field with limits and weekly step.",
      required: true,
      defaultValue: "2026-06-15T00:00:00.000Z",
      min: "2026-06-01T00:00:00.000Z",
      max: "2026-06-30T00:00:00.000Z",
      step: 7,
    },
    {
      id: "daily-signal",
      kind: "series",
      label: "Daily signal",
      description:
        "Date + numeric series that all backends read to build recommendation, latency and launch score.",
      required: true,
      defaultValue: [
        { field1: "2026-06-10", field2: 22 },
        { field1: "2026-06-11", field2: 24 },
        { field1: "2026-06-12", field2: 28 },
      ],
      minPoints: 2,
      maxPoints: 6,
      field1: {
        kind: "date",
        label: "Observed at",
        required: true,
        min: "2026-06-01T00:00:00.000Z",
        max: "2026-06-30T00:00:00.000Z",
      },
      field2: {
        kind: "number",
        label: "Signal value",
        required: true,
        min: 0,
        max: 100,
        unit: "pts",
      },
    },
    {
      id: "channel-performance",
      kind: "series",
      label: "Channel performance",
      description:
        "Category + numeric series mapping each deployment channel to its observed score.",
      defaultValue: [
        { field1: "Canary", field2: 91 },
        { field1: "Regional", field2: 78 },
      ],
      minPoints: 1,
      maxPoints: 4,
      field1: {
        kind: "category",
        label: "Channel",
        required: true,
        options: [
          { label: "Prototype", value: "Prototype" },
          { label: "Canary", value: "Canary" },
          { label: "Regional", value: "Regional" },
          { label: "Production", value: "Production" },
        ],
      },
      field2: {
        kind: "number",
        label: "Score",
        required: true,
        min: 0,
        max: 100,
        unit: "pts",
      },
    },
    {
      id: "feature-flags",
      kind: "series",
      label: "Feature flags",
      description:
        "Text + boolean series listing each feature flag and whether it is enabled for this release.",
      defaultValue: [
        { field1: "dark-launch", field2: true },
        { field1: "shadow-mode", field2: false },
      ],
      minPoints: 1,
      maxPoints: 8,
      field1: {
        kind: "text",
        label: "Flag name",
        required: true,
        minLength: 2,
        maxLength: 48,
        placeholder: "e.g. dark-launch",
      },
      field2: {
        kind: "boolean",
        label: "Enabled",
        required: true,
        trueLabel: "On",
        falseLabel: "Off",
      },
    },
    {
      id: "version-scores",
      kind: "series",
      label: "Version scores",
      description:
        "Text + category series pairing each model version with its quality tier.",
      defaultValue: [
        { field1: "v1.4.2", field2: "Canary" },
        { field1: "v1.5.0", field2: "Production" },
      ],
      minPoints: 1,
      maxPoints: 6,
      field1: {
        kind: "text",
        label: "Version",
        required: true,
        minLength: 2,
        maxLength: 24,
        placeholder: "e.g. v1.4.2",
      },
      field2: {
        kind: "category",
        label: "Tier",
        required: true,
        options: [
          { label: "Prototype", value: "Prototype" },
          { label: "Canary", value: "Canary" },
          { label: "Regional", value: "Regional" },
          { label: "Production", value: "Production" },
        ],
      },
    },
  ],
  reports: [
    ...BACKENDS.flatMap((backend) => [
      {
        id: `${backend.id}-recommendation`,
        kind: "classifier",
        label: `${backend.label} recommendation`,
        description: `${backend.label} backend classifier output.`,
        source: `${backend.id}.releaseRecommendation`,
        labels: CLASSIFIER_LABELS,
        details: true,
      },
      {
        id: `${backend.id}-latency`,
        kind: "regressor",
        label: `${backend.label} latency`,
        description: `${backend.label} backend latency forecast.`,
        source: `${backend.id}.latencyForecast`,
        unit: "ms",
        precision: 1,
      },
    ]),
    {
      id: "backend-compare",
      kind: "backend-compare",
      label: "Backend comparison",
      description: "Custom report that compares all backend outputs together.",
      backends: BACKENDS.map((backend) => backend.id),
      recommendationSource: "releaseRecommendation",
      latencySource: "latencyForecast",
      scoreSource: "launchScore",
    },
  ],
};
