export const QUESTIONNAIRE_SCHEMA = {
  steps: [
    {
      id: "identity",
      title: "Model identity",
      description: "Basic information about the model under evaluation.",
      fields: [
        {
          id: "model-name",
          kind: "text",
          label: "Model name",
          description: "Unique identifier for this model.",
          required: true,
          defaultValue: "gpt-eval-v2",
          placeholder: "e.g. gpt-eval-v2",
          minLength: 2,
          maxLength: 48,
        },
        {
          id: "quality-tier",
          kind: "category",
          label: "Quality tier",
          description: "Overall quality classification assigned to this model.",
          required: true,
          defaultValue: "beta",
          options: [
            { label: "Alpha", value: "alpha" },
            { label: "Beta", value: "beta" },
            { label: "RC", value: "rc" },
            { label: "Stable", value: "stable" },
          ],
        },
        {
          id: "approval",
          kind: "boolean",
          label: "Approved for deployment",
          description: "Whether this model passes the minimum quality bar.",
          required: true,
          defaultValue: false,
          trueLabel: "Approved",
          falseLabel: "Rejected",
        },
      ],
    },
    {
      id: "thresholds",
      title: "Thresholds",
      description: "Configure the minimum score requirements for this model.",
      fields: [
        {
          id: "accuracy-threshold",
          kind: "number",
          label: "Accuracy threshold",
          description: "Minimum required accuracy. Rendered as a range slider.",
          defaultValue: 0.8,
          min: 0,
          max: 1,
          step: 0.01,
          unit: "%",
        },
        {
          id: "training-epochs",
          kind: "number",
          label: "Training epochs",
          description: "Number of epochs used in fine-tuning.",
          required: true,
          defaultValue: 10,
          min: 1,
          max: 200,
          step: 1,
          unit: "epochs",
        },
      ],
    },
    {
      id: "benchmarks",
      title: "Benchmarks",
      description: "Enter benchmark results for this model.",
      fields: [
        {
          id: "benchmark-scores",
          kind: "series",
          label: "Benchmark scores",
          description: "Benchmark name paired with its score.",
          defaultValue: [
            { field1: "MMLU", field2: 78 },
            { field1: "HumanEval", field2: 65 },
          ],
          minPoints: 1,
          maxPoints: 10,
          field1: {
            kind: "text",
            label: "Benchmark",
            required: true,
            minLength: 1,
            maxLength: 32,
            placeholder: "e.g. MMLU",
          },
          field2: {
            kind: "number",
            label: "Score",
            required: true,
            min: 0,
            max: 100,
            unit: "pts",
          },
        },
        {
          id: "evaluation-date",
          kind: "date",
          label: "Evaluation date",
          description: "Date on which the benchmarks were run.",
          required: true,
          defaultValue: "2026-06-15T00:00:00.000Z",
          min: "2026-01-01T00:00:00.000Z",
          max: "2026-12-31T00:00:00.000Z",
        },
      ],
    },
    {
      id: "capabilities",
      title: "Capabilities",
      description: "Document supported capabilities and per-category performance ratings.",
      fields: [
        {
          id: "capability-flags",
          kind: "series",
          label: "Capability flags",
          description: "Each capability and whether it is supported.",
          defaultValue: [
            { field1: "tool-use", field2: true },
            { field1: "vision", field2: false },
          ],
          minPoints: 1,
          maxPoints: 12,
          field1: {
            kind: "text",
            label: "Capability",
            required: true,
            minLength: 2,
            maxLength: 40,
            placeholder: "e.g. tool-use",
          },
          field2: {
            kind: "boolean",
            label: "Supported",
            required: true,
            trueLabel: "Yes",
            falseLabel: "No",
          },
        },
        {
          id: "category-ratings",
          kind: "series",
          label: "Category ratings",
          description: "Task type paired with its performance rating.",
          defaultValue: [
            { field1: "reasoning", field2: "good" },
            { field1: "coding", field2: "excellent" },
          ],
          minPoints: 1,
          maxPoints: 8,
          field1: {
            kind: "category",
            label: "Task type",
            required: true,
            options: [
              { label: "Reasoning", value: "reasoning" },
              { label: "Coding", value: "coding" },
              { label: "Writing", value: "writing" },
              { label: "Math", value: "math" },
            ],
          },
          field2: {
            kind: "category",
            label: "Rating",
            required: true,
            options: [
              { label: "Poor", value: "poor" },
              { label: "Fair", value: "fair" },
              { label: "Good", value: "good" },
              { label: "Excellent", value: "excellent" },
            ],
          },
        },
      ],
    },
    {
      id: "feedback",
      title: "Feedback",
      description: "Qualitative feedback and ratings for this evaluation.",
      fields: [
        {
          id: "overall-rating",
          kind: "rating",
          label: "Overall rating",
          description: "Rate the model from 1 to 5. Arrow keys navigate between values.",
          required: true,
          defaultValue: 3,
          min: 1,
          max: 5,
          step: 1,
        },
        {
          id: "primary-use-case",
          kind: "single-choice",
          label: "Primary use case",
          description: "Select the main intended use case for this model.",
          required: true,
          defaultValue: "assistant",
          options: [
            { label: "Conversational assistant", value: "assistant" },
            { label: "Code generation", value: "code-gen" },
            { label: "Document summarisation", value: "summarisation" },
            { label: "Data extraction", value: "extraction" },
          ],
        },
        {
          id: "deployment-targets",
          kind: "multi-choice",
          label: "Deployment targets",
          description: "Select all environments where this model will be deployed.",
          required: true,
          defaultValue: ["cloud", "edge"],
          options: [
            { label: "Cloud (managed)", value: "cloud" },
            { label: "On-premise", value: "on-premise" },
            { label: "Edge / device", value: "edge" },
            { label: "Browser (WASM)", value: "browser" },
          ],
        },
        {
          id: "notes",
          kind: "long-text",
          label: "Evaluator notes",
          description: "Free-form observations, caveats or follow-up actions.",
          defaultValue: "",
          placeholder: "Add any relevant notes here…",
          maxLength: 1000,
        },
      ],
    },
  ],
};
